### ISSUE TITLE
Can't run `truffle test`

### ISSUE THREAD

**Issue by DucTrungNguyen** [DucTrungNguyen/xcoin#1]
when run `truffle test` have error below
`Error: 
    at Deployer._preFlightCheck (/usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:179:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:282:1
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:74:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:212:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:109:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/test/index.js:192:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:140:1)`

Still finding to reslove this problem

**Comment by DucTrungNguyen** [comment]
@hvquy001 how can i do with type problem? Thanks so much! Have nice weekeend

**Comment by hvquy001** [comment]
Check your truffle by `truffle version` command

**Comment by hvquy001** [comment]
You should keep `Migrations` contract

**Comment by hvquy001** [comment]
As well as `migrations/1_initial_migration.js`

**Comment by DucTrungNguyen** [comment]
that way make my struct of project not really clean! but, i will try. Thanks alot.
